### ISSUE TITLE
numpy.ufunc error while reproducing model based method results

### ISSUE THREAD

**Issue by zubair-irshad** [smlbansal/Visual-Navigation-Release#1]
Hi, 
While reproducing the model based method results, I am getting the following error: 

**ValueError: ('numpy.ufunc has the wrong size, try recompiling', 2, <OpenGL.platform.baseplatform.glGetShaderiv object at 0x7f6538094900>)**

This is a result of running the following commands from the read me file: 

**PYOPENGL_PLATFORM=egl PYTHONPATH='.' python executables/rgb/resnet50/rgb_waypoint_trainer.py test --job-dir reproduce_LB_WayptNavResults --params params/rgb_trainer/reproduce_LB_WayPtNav_results/rgb_waypoint_trainer_finetune_params.py -d 0**

I would appreciate your support in this regard. Thanks!

**Comment by vtolani95** [comment]
Hi,

Can you post the full stack trace please?

In the mean time, it seems that others have had [this issue](https://github.com/scipy/scipy/issues/3448) with packages being compiled against a different version of numpy than the one in the environment. 

Could you try manually reinstalling the offending packages in your environment (numpy, and probably pyopengl and pyopengl-accelerate)? You may have to try this a few times with different numpy versions to get one that works.

Thanks!

**Comment by zubair-irshad** [comment]
Here is the complete traceback: 

Traceback (most recent call last):
  File "executables/rgb/resnet50/rgb_waypoint_trainer.py", line 34, in <module>
    RGBWaypointTrainer().run()
  File "/home/mirshad7/Visual-Navigation-Release/training_utils/trainer_frontend_helper.py", line 25, in run
    self.setup_parser()
  File "/home/mirshad7/Visual-Navigation-Release/training_utils/trainer_frontend_helper.py", line 41, in setup_parser
    self.configure_parser(args)
  File "/home/mirshad7/Visual-Navigation-Release/training_utils/trainer_frontend_helper.py", line 75, in configure_parser
    self.test()
  File "/home/mirshad7/Visual-Navigation-Release/training_utils/visual_navigation_trainer.py", line 169, in test
    plot_controls=self.p.test.plot_controls)
  File "/home/mirshad7/Visual-Navigation-Release/training_utils/visual_navigation_trainer.py", line 54, in _init_simulator_data
    simulator = p.simulator(p)
  File "/home/mirshad7/Visual-Navigation-Release/simulators/sbpd_simulator.py", line 10, in __init__
    super(SBPDSimulator, self).__init__(params=params)
  File "/home/mirshad7/Visual-Navigation-Release/simulators/simulator.py", line 18, in __init__
    self.obstacle_map = self._init_obstacle_map(self.rng)
  File "/home/mirshad7/Visual-Navigation-Release/simulators/sbpd_simulator.py", line 56, in _init_obstacle_map
    return p.obstacle_map(p)
  File "/home/mirshad7/Visual-Navigation-Release/obstacles/sbpd_map.py", line 17, in __init__
    self._r = SBPDRenderer.get_renderer(self.p.renderer_params)
  File "/home/mirshad7/Visual-Navigation-Release/sbpd/sbpd_renderer.py", line 51, in get_renderer
    cls.renderer = cls(params)
  File "/home/mirshad7/Visual-Navigation-Release/sbpd/sbpd_renderer.py", line 28, in __init__
    r_obj = sr.get_r_obj(self.p.camera_params)
  File "/home/mirshad7/Visual-Navigation-Release/mp_env/render/swiftshader_renderer.py", line 512, in get_r_obj
    rgb_shader=rgb_shader, d_shader=d_shader, im_resize=cp.im_resize)
  File "/home/mirshad7/Visual-Navigation-Release/mp_env/render/swiftshader_renderer.py", line 181, in init_display
    os.path.join(dir_path, shader + '.fp'))
  File "/home/mirshad7/Visual-Navigation-Release/mp_env/render/swiftshader_renderer.py", line 255, in create_shaders
    assert(glGetShaderiv(v_shader, GL_COMPILE_STATUS) == 1)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
  File "wrapper.pyx", line 303, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6338)
  File "wrapper.pyx", line 88, in OpenGL_accelerate.wrapper.CArgCalculator.c_call (src/wrapper.c:2984)
  File "wrapper.pyx", line 69, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call (src/wrapper.c:2536)
  File "wrapper.pyx", line 64, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call (src/wrapper.c:2422)
  File "arraydatatype.pyx", line 317, in OpenGL_accelerate.arraydatatype.OutputOrInput.c_call (src/arraydatatype.c:6571)
  File "arraydatatype.pyx", line 226, in OpenGL_accelerate.arraydatatype.ArrayDatatype.c_zeros (src/arraydatatype.c:5090)
  File "arraydatatype.pyx", line 71, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_get_output_handler (src/arraydatatype.c:2407)
  File "arraydatatype.pyx", line 82, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_handler_by_plugin_name (src/arraydatatype.c:2579)
  File "/home/mirshad7/anaconda3/envs/venv-mpc/lib/python3.6/site-packages/OpenGL/plugins.py", line 16, in load
    return importByName( self.import_path )
  File "/home/mirshad7/anaconda3/envs/venv-mpc/lib/python3.6/site-packages/OpenGL/plugins.py", line 38, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/home/mirshad7/anaconda3/envs/venv-mpc/lib/python3.6/site-packages/OpenGL/arrays/numpymodule.py", line 27, in <module>
    from OpenGL_accelerate.numpy_formathandler import NumpyHandler
  File "__init__.pxd", line 861, in init OpenGL_accelerate.numpy_formathandler (src/numpy_formathandler.c:5849)
ValueError: ('numpy.ufunc has the wrong size, try recompiling', 2, <OpenGL.platform.baseplatform.glGetShaderiv object at 0x7f84b32db1f8>)

**Comment by zubair-irshad** [comment]
I have tried various numpy/scipy versions but I am getting the same error. Please let me know if you are able to figure out a different solution.

**Comment by vtolani95** [comment]
In this case it seems that there is version mismatch between the python OpenGL library and numpy. Can you try reinstalling the following packages and let us know how that goes?

pyopengl, pyopengl-accelerate, and numpy

**Comment by zubair-irshad** [comment]
I have tried manually installing these packages with the same version as mentioned in the environment file. The error persists.

**Comment by zubair-irshad** [comment]
Thanks Varun for reaching out offline to help resolve the issue. The solution is as follows: 
- Uninstall numpy, scipy, pyopengl and pyopengl-accelerate
- Reinstall the above libraries in the reverse order (pyopengl-accelerate first) using the --no-cache-dir flag
