### ISSUE TITLE
Test failed: test_coordinate_transform.py

### ISSUE THREAD

**Issue by Jiankai-Sun** [smlbansal/Visual-Navigation-Release#2]
Firstly, thank you for your brilliant work!

Followed your instruction [here](https://github.com/smlbansal/Visual-Navigation-Release#install-anaconda-gcc-g), we successfully build the environment. When we [Run the Tests](https://github.com/smlbansal/Visual-Navigation-Release#run-the-tests), the following error occurs, albeit we have checked that the .obj files are intact. We even replaced the provided .obj files with the files download directly from [here](https://github.com/alexsax/2D-3D-Semantics), the same error is still there.

Do you have any suggestions? Thank you.

Environment:
- Python 3.6
- Ubuntu 16.04

```bash
PYOPENGL_PLATFORM=egl PYTHONPATH='.' python executables/run_all_tests.py
======================================================================
Running test test_dynamics.py
rerun with visualize=True to visualize the test
rerun with visualize=True to visualize the test
Execution time for test test_dynamics.py is 2 seconds.
======================================================================
======================================================================
Running test test_cost_function.py
ERROR:root:Loading building from obj file: /home/developer/CodeSpace/Visual-Navigation-Release/data/LB_WayPtNav_Data/stanford_building_parser_dataset/mesh/area3/41a8012778ff4fc1800a7794bd15d81e.obj
ERROR:root:#Meshes: 90
Exception ignored in: <bound method Shape.__del__ of <mp_env.render.swiftshader_renderer.Shape object at 0x7faa3c9a0e10>>
Traceback (most recent call last):
  File "/home/developer/CodeSpace/Visual-Navigation-Release/mp_env/render/swiftshader_renderer.py", line 157, in __del__
  File "/home/developer/anaconda3/envs/venv-mpc/lib/python3.6/site-packages/pyassimp/core.py", line 351, in release
ImportError: sys.meta_path is None, Python is likely shutting down
Execution time for test test_cost_function.py is 12 seconds.
======================================================================
======================================================================
Running test test_coordinate_transform.py
Traceback (most recent call last):
  File "/home/developer/CodeSpace/Visual-Navigation-Release/tests/test_coordinate_transform.py", line 179, in <module>
    test_rotate()
  File "/home/developer/CodeSpace/Visual-Navigation-Release/tests/test_coordinate_transform.py", line 44, in test_rotate
    new_pos_112 = rotate_pos_nk2(pos_112, theta_111)
  File "/home/developer/CodeSpace/Visual-Navigation-Release/utils/angle_utils.py", line 22, in rotate_pos_nk2
    pos_rot_nk2 = tf.matmul(rot_matrix_nk22, pos_nk2[:, :, :, None])[:, :, :, 0]
  File "/home/developer/anaconda3/envs/venv-mpc/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1980, in matmul
    a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
  File "/home/developer/anaconda3/envs/venv-mpc/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1261, in batch_mat_mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Blas xGEMV launch failed : a.shape=[1,2,2], b.shape=[1,2,1], m=2, n=1, k=2 [Op:BatchMatMul] name: MatMul/
Execution time for test test_coordinate_transform.py is 2 seconds.
======================================================================
Test failed: test_coordinate_transform.py
```

**Comment by vtolani95** [comment]
Hello,

Firstly, thanks for your interest in our codebase!

The following error is actually expected behavior:
`
ERROR:root:Loading building from obj file: /home/developer/CodeSpace/Visual-Navigation-Release/data/LB_WayPtNav_Data/stanford_building_parser_dataset/mesh/area3/41a8012778ff4fc1800a7794bd15d81e.obj
ERROR:root:#Meshes: 90
Exception ignored in: <bound method Shape.__del__ of <mp_env.render.swiftshader_renderer.Shape object at 0x7faa3c9a0e10>>
Traceback (most recent call last):
  File "/home/developer/CodeSpace/Visual-Navigation-Release/mp_env/render/swiftshader_renderer.py", line 157, in __del__
  File "/home/developer/anaconda3/envs/venv-mpc/lib/python3.6/site-packages/pyassimp/core.py", line 351, in release
ImportError: sys.meta_path is None, Python is likely shutting down
`

We will put a patch on this eventually, but for the moment all these lines are expected to print out when you run the code (we get the same lines printed out on our end as well).

Cheers,
Varun
